fix: split publish errors to separate lines
datreeio/datree pull request #211
Opened 2021-10-19 13:47 UTC by myishay

2021-10-19 15:07 UTC, dimabru commented on cmd/publish/main.go
> +	if publishErr != nil {
return `publishErr` if exists

2021-10-19 15:07 UTC, dimabru submitted a review, later dismissed

2021-10-20 08:46 UTC, noaabarki requested changes

2021-10-20 08:46 UTC, noaabarki commented on cmd/publish/main.go
> +	PublishPolicies(policiesConfiguration files.UnknownStruct, cliId string) (httpClient.Response, error)
Let's return a pointer `*httpClient.Response`

2021-10-20 08:46 UTC, noaabarki commented on cmd/publish/main.go
> +	PublishPolicies(policiesConfiguration files.UnknownStruct, cliId string) (httpClient.Response, error)
I'm pretty sure the CliClient shouldn't be exported or used outside of publish package. If I'm not mistaken, let's use `cliClient` instead

2021-10-20 08:46 UTC, noaabarki commented on cmd/publish/main.go
> +					ctx.Printer.PrintMessage("Publish failed:\n", "error")
Why twice `"Publish failed:\n", "error"`?

2021-10-20 08:46 UTC, noaabarki commented on cmd/publish/main.go
> +type PublishFailedResponse struct {
The same comment on the `CliClient` -> `cliClient`

2021-10-20 08:46 UTC, noaabarki commented on cmd/publish/main.go
> +func publish(ctx *PublishCommandContext, path string) (PublishFailedResponse, error) {
Please return pointer instead of new value

2021-10-20 08:46 UTC, noaabarki commented on pkg/cliClient/publish.go
> +func (c *CliClient) PublishPolicies(policiesConfiguration files.UnknownStruct, cliId string) (httpClient.Response, error) {
👆🏼

2021-10-20 08:46 UTC, noaabarki commented on pkg/cliClient/cliClient_test.go
> +
Do the tests cover what you added?

2021-10-24 13:54 UTC, merged