feat: use stale action to mark stale issues
datreeio/datree pull request #236
Opened 2021-10-26 00:08 UTC by prasadkatti

Fixes: #231

2021-10-26 05:29 UTC, eyarz requested changes

2021-10-26 05:29 UTC, eyarz commented on .github/workflows/stale.yml
> +    - cron: '0 */6 * * *'
In all the [examples](https://github.com/actions/stale#usage), they (github) run the cron job once a day (`30 1 * * *`). Do you have a reason why you decided to set it to every 6h?

2021-10-26 07:16 UTC, prasadkatti commented on .github/workflows/stale.yml
> +    - cron: '0 */6 * * *'
No particular reason. Just thought it would be better to run it more frequently than once a day. But I will stick to the convention and change it back.

2021-10-27 06:42 UTC, romanlab submitted a review, later dismissed

2021-10-27 08:16 UTC, eyarz submitted a review, later dismissed

2021-10-27 10:19 UTC, dimabru commented
Staging branch is deprecated and will soon be deleted.
Our new default branch in main.
Please change your pr to merge to main.
Thanks!!

2021-10-28 12:24 UTC, eyarz approved these changes

2021-10-28 12:33 UTC, merged