feat: Command auto completion option to terminal datreeio#183
datreeio/datree pull request #237
Opened 2021-10-26 05:18 UTC by imrushi

Added the command auto-completion like datree [tab][tab] it will give all following commands version, completion, config, test...

```
$ datree [tab][tab]
completion  config      help        publish     test        version
```
To test follow the below steps:
1. compile code with `go build -o datree main.go`
2. `./datree completion -h` we will get a description of how to use the completion command for [bash|zsh|fish|powershell].
3. For example bash we will use 
`$ datree completion bash > /etc/bash_completion.d/datree`
`$ source /etc/bash_completion.d/datree`
4. Now you will get auto-completion of command like below
```
$ datree [tab][tab]
completion  config      help        publish     test        version
$ datree completion [tab][tab]
bash        fish        powershell  zsh
```

2021-10-26 10:34 UTC, dimabru requested changes
Thanks! This is a great pr!!
I made some comments, should be small and easy fixes

2021-10-26 10:34 UTC, dimabru commented on cmd/completion/main.go
> +type CompletionCommandContext struct {
Unlike other commands, `completion` has no dependenies on external logic. Since you're not using any of the completion command context paramteres, you can delete the type itself

2021-10-26 10:34 UTC, dimabru commented on cmd/completion/main_test.go
> +	// repalce bash with zsh, fish, powershell as per var b & SetArgs
I think the test should cover all potential flags. I removed the powershell flag and the test passed succesfully

2021-10-26 10:34 UTC, dimabru commented on cmd/completion/main_test.go
> +	if string(out) != "bash" {
We should (at least partially), make sure the output matches the expected output of the completion command. Here you only check for the flag.
Maybe just check the first line of the output matches `# bash completion for datree` ?

2021-10-26 12:03 UTC, imrushi commented on cmd/completion/main_test.go
> +	if string(out) != "bash" {
Could you please provide an example if you have any?
also could you please elaborate more `Maybe just check the first line of the output matches # bash completion for datree ?`

2021-10-26 15:14 UTC, imrushi commented on cmd/completion/main_test.go
> +	if string(out) != "bash" {
oh, I got it.

2021-10-26 15:25 UTC, dimabru commented on cmd/completion/main_test.go
> +	if string(out) != "bash" {
:-)

2021-10-26 17:38 UTC, imrushi commented on cmd/completion/main_test.go
> +	if string(out) != "bash" {
Hey @dimabru, 
Can you please help me with how should I get the output of a command that is I am executing from the test file? I am so stuck at this point.

2021-10-27 10:19 UTC, dimabru commented
Staging branch is deprecated and will soon be deleted.
Our new default branch in main.
Please change your pr to merge to main.
Thanks!!

2021-10-27 12:37 UTC, imrushi commented
Hi @dimabru,
Please review, all required fixes/changes are done.

2021-10-27 13:11 UTC, dimabru requested changes

2021-10-27 13:11 UTC, dimabru commented on cmd/completion/main_test.go
> +	cmd.Run = func(cmd *cobra.Command, args []string) {
The unit-tests role is to test the logic of the cmd. Here you override the logic we want to test. If I go to the completion cmd file and delete or modify all the code there, this test will still pass because it has nothing to do with the actual command.

I recommend having a look here: https://github.com/datreeio/datree/blob/main/pkg/printer/printer_test.go
we tested the printer package with override for the os.Stdout method. That way we're able to make sure the function outputs what we want.

Also, please make sure you cover all possible outputs

2021-10-28 13:43 UTC, imrushi commented
As per your recommendation, I have made the required changes. Please have a look at it.
I have tried to cover all possible checks from my end.
Please review.

2021-10-31 10:35 UTC, dimabru approved these changes

2021-10-31 11:41 UTC, merged