fix: use pull_request instead of push
datreeio/datree pull request #260
Opened 2021-10-31 12:03 UTC by kevholmes

When reviewing the original issue #205 it sounds like this was only supposed to run on `pull_request` events. My fix will ensure that this only runs when contributors submit a PR to the datree repo.

2021-10-31 12:12 UTC, romanlab commented
Actually, it would be great to give the contributor an indication before submitting a PR. It's ok that it runs on a `push` event, it just needs to ignore the `main` branch. If we do it this way, we can then refactor the script and use it with pre-commit.

maybe you can use 
```
on: 
  push:
    branches-ignore:
      - 'main'
``` 

to achieve that

WDYT?

2021-10-31 12:28 UTC, kevholmes commented
I like the idea of adding the python script as a local pre-commit hook, that way the contributor could see the issue before they ever make a commit.

I'd say it's a pretty minute difference between `push` and `pull_request` really. If I fork datree's GH repo and push commits directly to my feature branch the `push` trigger _might_ run (as long as I have manually gone in and enabled Actions for my forked repo.) So it's not exactly automated for end users. I like reducing the scope of when this runs to something more narrow like `pull_request` as a good practice as the blanket on `push` could overlap with other git repo work you're doing that might not need to meet that Check's criteria and cause an unnecessary failure.

2021-10-31 12:39 UTC, romanlab commented
@kevholmes That's a valid point. But looking at the event structure for a `pull_request` event, i didn't see a `commits` key and not sure the script will work for the event. You can see the details [here](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request)

2021-10-31 12:40 UTC, kevholmes commented
> @kevholmes That's a valid point. But looking at the event structure for a `pull_request` event, i didn't see a `commits` key and not sure the script will work for the event. You can see the details [here](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request)

`pull_request` is a little confusing - they call the events `synchronize` when pushing follow-up commits to a PR. I think because of how GH handles PRs behind the scenes.

2021-10-31 12:46 UTC, romanlab commented
> > @kevholmes That's a valid point. But looking at the event structure for a `pull_request` event, i didn't see a `commits` key and not sure the script will work for the event. You can see the details [here](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request)
> 
> `pull_request` is a little confusing - they call the events `synchronize` when pushing follow-up commits to a PR. I think because of how GH handles PRs behind the scenes.

That's fine, i see the `synchronize` action but the event structure doesn't have a `commits` key. I approved the workflow, you can see the check failing

2021-10-31 12:54 UTC, kevholmes commented
Ahh ok, I see what you're saying @romanlab regarding the python [script](https://github.com/datreeio/datree/blob/main/scripts/check_commit_messages.py) possibly not working with this approach. It seems like we really want to run something that examines the GH PR's `title` and gives feedback regarding if they meet the standard or not. Each commit to a PR might not follow the approach, but ultimately its the PR `title` that will get squashed-and-merged into `main` and should follow the spec.

2021-10-31 13:09 UTC, kevholmes commented
Maybe using something like [this](https://github.com/marketplace/actions/pr-title-checker) to review the PR titles?

2021-10-31 13:13 UTC, romanlab commented
> Maybe using something like [this](https://github.com/marketplace/actions/pr-title-checker) to review the PR titles?

We prefer to not have external dependencies on projects with almost no community. `pr-title-checker` has only 31 stars. It'll be easier to adjust the script to validate the pr title.

2021-10-31 17:12 UTC, kevholmes commented
@romanlab How about this? I've refactored the python script and workflow to handle PR title checking instead of commit message checking. This has a more narrow scope and I think it meets the team's criteria. I have added some additional error handling to the python script as I noticed issues with errors when attempting to parse a `:` that might not be in the message if the author forgot it.

I used some sample output from a test PR in my fork of datree's repo to test the Python script, here's the [sample json](https://gist.github.com/kevholmes/e9b18991c1be82535147a7695d4f2661).

2021-10-31 17:27 UTC, kevholmes commented
I've got some sample code running in my public fork if you'd like to review it there: https://github.com/kevholmes/datree/pull/2

2021-11-01 08:37 UTC, romanlab requested changes

2021-11-01 08:37 UTC, romanlab commented on .github/workflows/check_pr_title.yml
> +  check:
Please change the script file name to the new name in the `run` command, the workflow fails at the moment.

2021-11-01 16:44 UTC, kevholmes commented on .github/workflows/check_pr_title.yml
> +        run: python ./scripts/check_pr_title.py.py
😆 I'll fix this now.

2021-11-01 23:25 UTC, romanlab approved these changes

2021-11-02 08:14 UTC, merged