perf: read files in parallel
datreeio/datree pull request #452
Opened 2022-02-27 07:40 UTC by vbh

Closes #447

2022-03-06 10:16 UTC, shalev007 commented
Hey, @vbh Thank you for your contribution!
We're starting to review your PR now,
I updated your branch with the latest changes

2022-03-06 10:19 UTC, shalev007 commented
@noaabarki I remember you did something similar, would you like to give your thought on this?

2022-03-07 20:15 UTC, noaabarki requested changes, later dismissed
Great work @vbh! Great to have you on board with us! 🏆

2022-03-07 20:15 UTC, noaabarki commented on bl/files/files.go
> +	go func() {
For clarity, I suggest to wrap this in a private method maybe `parsePathsArrayToChan()`

2022-03-07 20:15 UTC, noaabarki commented on bl/files/files.go
>  		defer func() {
No need to use defer, we can close both channels after `wg.Wait()`

2022-03-07 20:15 UTC, noaabarki commented on bl/files/files.go
> +				for path := range pathsChan {
How about using using a for loop with `path, ok := <- pathChan` to make sure we read form pathsChan until it's both empty and closed?

2022-03-12 18:34 UTC, noaabarki commented
/LGTM @dimabru @shalev007

2022-03-13 11:32 UTC, mashtuba commented
Hi @vbh, thanks for submitting the PR! 🙌
We’re currently working on moving our evaluation process to the CLI, therefore we’re in a code-freeze until we merge these changes.
Your PR will be reviewed and merged once we’re out from code freeze, by the end of next week 🥳

2022-03-13 11:39 UTC, adifay commented
Hi @vbh, thanks for submitting the PR! 🙌
We’re currently working on moving our evaluation process to the CLI, therefore we’re in a code-freeze until we merge these changes.
Your PR will be reviewed and merged once we’re out from code freeze, by the end of next week 🥳

2022-03-30 13:10 UTC, shalev007 commented
Hi @vbh,
Just an update,
were out of the code freeze and I'll take a look at the PR as soon as I can, so we can push this further

2022-04-10 14:38 UTC, shalev007 commented
Sorry for the late response,
We had to validate this works for edge cases as well and found an issue,
for example:
- if we read more files than the `concurrency` variable the test is stuck 

possible fix: on `cmd/test/main.go` on line 414 please use the function as a go routine ie: `go validationManager.AggregateInvalidYamlFiles(invalidYamlFilesChan)`

Could you please add that and check edge cases such as a big amount of files? 🙏 
We're also available on our community [slack channel](https://datreecommunity.slack.com/archives/C02L0QB3YTC) for any discussion

2022-04-14 11:05 UTC, myishay commented
@vbh ping 😊
any news on this one?

2022-04-17 11:06 UTC, shalev007 commented
@vbh
I was testing your changes and it appears it still doesn't work when there are more files than the concurrent files
example:
1. change the concurrency to 2 (`concurrency := 2`)
2. compile (`make build-staging`)
3. and run `./datree ./internal/fixtures/kube/empty.yaml ./internal/fixtures/kube/empty.yaml ./internal/fixtures/kube/empty.yaml`

2022-04-27 05:49 UTC, shalev007 approved these changes

2022-04-27 06:33 UTC, merged