Dat 3845 add offline flag in config yaml
datreeio/datree pull request #517
Opened 2022-03-21 13:40 UTC by TzlilSwimmer123

2022-03-21 15:07 UTC, TzlilSwimmer123 commented
Need to add more tests and open for design refactor

2022-03-21 16:26 UTC, alexfedin requested changes
@TzlilSwimmer123 missing handling the reportErrors requests in main.go so they will be ignored too, in general if you will put the logic to ignore network errors inside the cliClient you won't have to worry about where it's being used and it will hold for future requests as well

2022-03-21 16:26 UTC, alexfedin commented on cmd/kustomize/main.go
> +				evaluationPrerunData, err = testCtx.CliClient.RequestEvaluationPrerunData(localConfigContent.Token)
it looks like the way isBackendAvailable is being used is always the same

Move the `isBackednAvailable` logic inside the clients function so that it will be exposed only to cliClient, that way when you request something and backend is down the cliClient function will return the empty value of what you request because that's what you're doing here anyway.

This will also require the offline parameter to be passed to the cliClient so it will know if it should return an error or an empty value

2022-03-22 15:55 UTC, dimabru commented
@TzlilSwimmer123 
bump this to version 1.1.0 :)

2022-03-23 10:30 UTC, dimabru requested changes
@TzlilSwimmer123
bump this to version 1.1.0 :)

2022-03-23 15:46 UTC, MentalBrake approved these changes, later dismissed

2022-03-23 17:16 UTC, dimabru submitted a review, later dismissed

2022-03-24 14:23 UTC, alexfedin approved these changes

2022-03-24 14:25 UTC, merged