Test case added
datreeio/datree pull request #522
Opened 2022-03-22 14:39 UTC by sourikghosh

closes #443

changes:
- relocated test-cases for ToAbsolutePath 
- added test-cases for ExtractConfigurationsFromYamlFile

2022-03-22 14:43 UTC, sourikghosh commented
review @noaabarki @MentalBrake

2022-03-30 10:29 UTC, TzlilSwimmer123 commented
Thanks for your effort @sourikghosh. We will look into it in the next couple of days 🙏

2022-03-31 12:29 UTC, TzlilSwimmer123 requested changes
Hi @sourikghosh,
Really appreciate your time and work.

Left some comments :)

2022-03-31 12:29 UTC, TzlilSwimmer123 commented on pkg/extractor/extractor_test.go
> +		actualVal, actualStr, actualErr := ExtractConfigurationsFromYamlFile("")
I think that `actualVal, actualStr, actualErr` are not easy to understand what we expect the function to return, if I want to know it I need to go the function declaration. What do you think about renaming in to something more meaningful like `configurations, absolutePath, ...`

2022-03-31 12:29 UTC, TzlilSwimmer123 commented on pkg/extractor/extractor_test.go
> +		assert.Equal(t, "", actualStr)
I think that it's a good practice to create new variable for empty string and use it here and when you call the function. Prevent using `""` twice

2022-03-31 12:29 UTC, TzlilSwimmer123 commented on pkg/extractor/extractor_test.go
> +		actualVal, actualResult, actualErr := ExtractConfigurationsFromYamlFile(path)
Same comment about renaming

2022-03-31 12:29 UTC, TzlilSwimmer123 commented on pkg/extractor/extractor_test.go
> +		assert.EqualValues(t, "yaml validation error: yaml: line 2: did not find expected key\n", actualErr.ValidationErrors[0].Error())
I think you used `assert.EqualValues` to check if 2 objects are equal but now you check for a string value so it's redundant. You can use `Equal`

2022-03-31 12:29 UTC, TzlilSwimmer123 commented on pkg/extractor/extractor_test.go
> +		actualValue, actualResult, actualErr := ExtractConfigurationsFromYamlFile(path)
Same comment about renaming

2022-03-31 12:29 UTC, TzlilSwimmer123 commented on pkg/extractor/extractor_test.go
> +	t.Run("valid yaml file, should return a Configuration and no error", func(t *testing.T) {
I think it's better to align the capitalization and put `configuration`

2022-04-03 09:19 UTC, TzlilSwimmer123 approved these changes
Looks good!!!
Thanks

2022-04-04 09:12 UTC, merged