feat: display configs count
datreeio/datree pull request #54
Opened 2021-05-31 17:31 UTC by dimabru

2021-06-01 11:36 UTC, MentalBrake requested changes

2021-06-01 11:36 UTC, MentalBrake commented on cmd/test/main.go
> +func countConfigurations(filesConfigurations []*extractor.FileConfiguration) int {
I think we should move this into the format function in evaluator if no one else is using filesConfigurations parameter down the line

2021-06-01 13:15 UTC, MentalBrake approved these changes

2021-06-01 13:15 UTC, MentalBrake commented on bl/evaluation/printer.go
>  	totalRulesEvaluated := 0
test comment

2021-06-02 08:11 UTC, dimabru commented on cmd/test/main.go
> +func countConfigurations(filesConfigurations []*extractor.FileConfiguration) int {
`filesConfigurations` is used below

2021-06-02 08:11 UTC, merged