Dat 4075 yml validation array
datreeio/datree pull request #644
Opened 2022-05-25 13:41 UTC by shmuelsa

2022-05-29 14:38 UTC, noaabarki requested changes

2022-05-29 14:38 UTC, noaabarki commented on bl/validation/k8sValidator.go
> +		return "", ""
I think it's better to return error in this case

2022-05-29 14:38 UTC, noaabarki commented on pkg/extractor/extractor.go
> +func ParseJsonToK8sValues(content []byte) (map[string]interface{}, error) {
I think the name is a little odd. It's not necessarily JSON it's basically any byte array and it's unclear what is `k8sValues`.

2022-05-29 14:38 UTC, noaabarki commented on pkg/extractor/extractor.go
> +	if err != nil && err != io.EOF {
IMHO, `extractYamlConfigurations` should not return `io.EOF` if it's meaninigless.

2022-05-29 14:38 UTC, noaabarki commented on pkg/cliClient/cliClient_test.go
> +		var anyTypeStore interface{}
Implementing the function again is a bit weird.  Anyway, I think we can delete `readMock`

2022-05-29 14:38 UTC, noaabarki commented on pkg/extractor/extractor.go
> +		yamlByteArray, err := yaml.Marshal(anyTypeStore)
I miss your comments, it made it much more clear to understand why we decode every YAML, marshal it and then parse it to JSON.

2022-05-29 14:39 UTC, noaabarki commented
I think naming `configuration []byte ` just makes the code much more complex to understand. To me, `Configuration` has no longer meaning at this point, it is basically `[]bytes`. It's not a blocker but we can talk about it and review the full flow to see how we can improve it

2022-05-30 13:07 UTC, myishay commented on bl/validation/k8sValidator.go
> +type MetadataAndKind struct {
no need for this type

2022-05-30 13:14 UTC, myishay commented on pkg/extractor/extractor.go
> +func extractMetadataNameAndKind(content []byte) Configuration {
I think we should rename to something like `extractConfigurationMetadata` since it get's now also Annotations, apiVersion etc.

2022-05-30 14:01 UTC, myishay approved these changes

2022-05-30 14:04 UTC, noaabarki approved these changes

2022-05-30 14:48 UTC, shalev007 commented on pkg/extractor/extractor.go
> +	configuration.Payload = content
is Payload the original content (string of the yaml)?
maybe you can change it to a name that explains better what that is like `rawJson`?

2022-05-30 14:48 UTC, shalev007 commented on bl/evaluation/evaluator.go
>  		if strings.Contains(annotationKey, SKIP_RULE_PREFIX) {
read my mind!!!
king 👑

2022-05-30 14:49 UTC, merged