Line err
datreeio/datree pull request #772
Opened 2022-08-29 13:12 UTC by shmu3l

2022-08-30 13:06 UTC, hadar-co commented
![Screen Shot 2022-08-30 at 16 04 32](https://user-images.githubusercontent.com/96784606/187444235-95ee99df-3d46-4100-a7e0-ecf20636f2f1.png)

2022-09-01 10:39 UTC, royhadad requested changes

2022-09-01 10:39 UTC, royhadad commented on pkg/cliClient/evaluation.go
> +type ValidationResult struct {
rename to `FailureLocation`?

2022-09-01 10:39 UTC, royhadad commented on pkg/extractor/extractor.go
> +	configuration.YamlNode = yamlNode
should be lower case `configuration.yamlNode`

2022-09-01 10:39 UTC, royhadad commented on pkg/printer/printer_test.go
> +					FailedErrorColumn: 0,
make line and column different, this way the test case will catch more cases, when someone accidentally flips the printing. (better value for money in the same test

2022-09-01 10:39 UTC, royhadad commented on pkg/printer/printer_test.go
> +
do we want the extra space here? (this is a product question)

2022-09-01 10:39 UTC, royhadad commented on pkg/evaluation/evaluator.go
> +func updateFailedRuleLine(schemaPath string, yamlNode yaml.Node) (failedErrorLine int, failedErrorColumn int) {
rename method `get...` :)

2022-09-01 10:39 UTC, royhadad commented on pkg/evaluation/evaluator.go
> +func yqlibLoggerHandler() {
What is this? please explain it to me face2face :)

2022-09-01 10:39 UTC, royhadad commented on pkg/evaluation/evaluator.go
> +func updateFailedRuleLine(schemaPath string, yamlNode yaml.Node) (failedErrorLine int, failedErrorColumn int) {
now that this method is **pure** we can (and should) add a unit test for it, there is some complex logic here

2022-09-01 10:39 UTC, royhadad commented on pkg/evaluation/evaluator.go
> +	instanceLocationYqPath := strings.Replace(schemaPath, "/", ".", -1)
please explain this method to me face2face :)

2022-09-01 13:46 UTC, royhadad commented on pkg/evaluation/evaluator_test.go
> +	yamlNode := yaml.Node{
embded a real yaml and convert it to `yaml.Node`

2022-09-01 13:47 UTC, myishay commented on pkg/cliClient/evaluation.go
> +	FailureLocations []FailureLocation `json:"FailureLocation"`
json tag should be lowercased

2022-09-01 15:53 UTC, myishay commented on pkg/printer/printer.go
> +						errorPath := fmt.Sprintf("%v (line: %d:%d)\n", strings.Replace(validationResult.SchemaPath, "/", ".", -1)[1:], validationResult.FailedErrorLine, validationResult.FailedErrorColumn)
ins this an error? or a failure of the rule?

2022-09-01 15:59 UTC, myishay approved these changes, later dismissed

2022-09-01 16:12 UTC, royhadad approved these changes

2022-09-01 16:14 UTC, merged