feat: add All_Rules policy
datreeio/datree pull request #804
Opened 2022-09-25 07:55 UTC by shalev007

2022-09-25 11:58 UTC, TzlilSwimmer123 requested changes
just making sure we need "" or not in each `messageOnFailure`

2022-09-25 11:58 UTC, TzlilSwimmer123 commented on pkg/defaultPolicies/defaultPolicies.yaml
> +        messageOnFailure: "Incorrect value for key `schedule` - the (cron) schedule expressions is not valid and, therefore, will not work as expected"
Why do we need "" here and in there other no?

2022-10-02 07:38 UTC, shmu3l approved these changes

2022-10-02 07:56 UTC, TzlilSwimmer123 approved these changes

2022-10-02 09:17 UTC, merged