feat:add configuration for schema_locations, policy_config in config
datreeio/datree pull request #927
Opened 2023-04-11 11:51 UTC by Meyazhagan

related issue - #737

2023-04-13 08:47 UTC, adifayer commented
Thank you for raising this PR! @Meyazhagan We will look into it in the upcoming days 🤩

2023-04-18 08:27 UTC, niv1612 requested changes

2023-04-18 08:27 UTC, niv1612 commented on pkg/localConfig/localConfig.go
> +	tranformedValue := transformValue(key, value)
The name `transformValue` isn’t indicative. I would suggest simply writing an inline if-else statement, something like this:
```
if key == policyConfigKey {
viper.Set(....)
} else if ....
```

2023-04-18 08:27 UTC, niv1612 commented on cmd/test/main.go
> +	policyConfigEnv := os.Getenv(DatreePolicyConfig)
Can you please explain why the environment variable is being used in this context? I’m not quite sure of its purpose and would appreciate some clarification.

2023-04-18 08:27 UTC, niv1612 commented on cmd/test/main.go
> +		if policyConfig == "" {
I noticed that there are two identical if statements. Was it made by mistake? It appears to be a potential bug

2023-04-18 08:27 UTC, niv1612 commented on cmd/test/main.go
> +	if len(schemaLocations) == 0 {
Same here (two identical if statements). Was it made by mistake? If not, could you explain?

2023-04-20 12:17 UTC, Meyazhagan commented on cmd/test/main.go
> +		if policyConfig == "" {
Not sure why I went with this approach. I was looking for `??` in go lang, wonder go was not support. May be that influenced.

I rewrote these conditions. Take a look at.

2023-04-20 12:17 UTC, Meyazhagan commented on pkg/localConfig/localConfig.go
> +	tranformedValue := transformValue(key, value)
I too love this simple way. I changed this to inline if-else

2023-04-24 10:42 UTC, niv1612 commented on cmd/test/main.go
> +	policyConfigEnv := os.Getenv(DatreePolicyConfig)
@Meyazhagan  I see that you are still using the environment variable for policyConfig. Can you explain why? We don't use environment variables currently in this context.

2023-04-25 02:02 UTC, Meyazhagan commented on cmd/test/main.go
> +	policyConfigEnv := os.Getenv(DatreePolicyConfig)
@niv1612 the user described, the solution to set policyConfig, either by config or env. 

> Order for reading values-
CLI flag command > Env variable > Config file

I didn't find a place for env wrapper like we have for localConfig. So I used it directly here.

2023-05-01 14:50 UTC, niv1612 approved these changes

2023-05-01 22:58 UTC, merged