feat:exclude paths regex
datreeio/datree pull request #932
Opened 2023-05-03 17:48 UTC by Meyazhagan

related issues - #732

2023-05-04 12:11 UTC, adifayer commented
@Meyazhagan  Thank you for raising this PR 🤩 We will review it in the upcoming days

2023-05-08 15:18 UTC, royhadad requested changes

2023-05-08 15:18 UTC, royhadad commented on pkg/fileReader/reader.go
> +	excludeRe, err := regexp.Compile(excludePattern)
This is good, but missing a more explicit validation in: https://github.com/datreeio/datree/blob/5daac43f7db044b4479c346c776b6b7d118a4559/cmd/test/main.go#L96

the error message can be: "invalid --exclude flag: <THE_ERROR>"

2023-05-08 15:18 UTC, royhadad commented on pkg/fileReader/reader.go
> +func (fr *FileReader) FilterFiles(paths []string, excludePattern string) ([]string, error) {
please add some unit tests, I suggest starting with `reader_test.go` :)

2023-05-08 15:18 UTC, royhadad commented on pkg/fileReader/reader.go
> +	excludeRe, err := regexp.Compile(excludePattern)
just a suggestion :)
```suggestion
	excludeRegex, err := regexp.Compile(excludePattern)
```

2023-05-08 15:42 UTC, royhadad commented on cmd/test/main.go
> +	cmd.Flags().StringVarP(&flags.ExcludePattern, "exclude", "", "", "Exclude paths pattern")
```suggestion
	cmd.Flags().StringVarP(&flags.ExcludePattern, "exclude", "", "", "Exclude paths pattern (regex)")
```

2023-05-08 15:43 UTC, royhadad commented
requested some minor suggestions, should be pretty straight forward :)

2023-05-09 17:33 UTC, Meyazhagan commented
@royhadad  I have made the changes. Take a look !

2023-05-10 11:46 UTC, royhadad approved these changes
looking good! 🚀🚀🚀

2023-05-10 11:47 UTC, merged

2023-05-10 13:18 UTC, royhadad commented
@Meyazhagan 
This PR is included in the latest 1.9.0 release 🥳🥳, thank you for contributing! 🚀