fix: update name rule logic to ignore incorrect kinds
datreeio/datree pull request #957
Opened 2023-07-11 12:33 UTC by hadar-co

2023-07-11 13:03 UTC, royhadad submitted a review, later dismissed

2023-07-11 13:07 UTC, royhadad requested changes

2023-07-11 13:07 UTC, royhadad commented on pkg/defaultRules/defaultRules.yaml
> +                - ClusterRole
This means `ClusterRole` can omit the `name` field altogether, I think this should be separated into 2 cases:
1. enforce the `name` field for all relevant resources
2. enforce the `name` field format only for some of those resources

2023-07-11 13:09 UTC, myishay approved these changes, later dismissed
👑

2023-07-11 15:36 UTC, hadar-co commented on pkg/defaultRules/defaultRules.yaml
> +                - ClusterRole
good catch! @royhadad

2023-07-11 15:42 UTC, royhadad requested changes
I see some problems here, call me

2023-07-12 09:09 UTC, royhadad approved these changes, later dismissed

2023-07-12 09:09 UTC, royhadad commented on pkg/defaultRules/defaultRules.yaml
> +              metadata:
should `metadata` be required?

2023-07-12 09:15 UTC, royhadad approved these changes

2023-07-12 09:16 UTC, merged